# Generated by Django 5.2 on 2026-05-15 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='role',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
