# Generated by Django 5.2 on 2026-05-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True, unique=True),
        ),
    ]
