# Generated by Django 5.2 on 2026-05-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
