# Generated by Django 6.0.4 on 2026-05-25 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='El código debe tener formato YY-000', regex='^\\d{2}-\\d{3}$')]),
        ),
    ]
