# Generated by Django 6.0.4 on 2026-05-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projecttemplate_tasktemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttemplate',
            name='perfect_for',
            field=models.TextField(blank=True),
        ),
    ]
