# Generated by Django 6.0.4 on 2026-05-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_projecttemplate_perfect_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttemplate',
            name='generated_from',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projecttemplate',
            name='perfect_for',
            field=models.TextField(blank=True, help_text='Uso orientativo del template'),
        ),
    ]
