# Generated by Django 6.0.4 on 2026-05-31 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_projecttemplate_generated_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.projecttemplate'),
        ),
        migrations.AlterField(
            model_name='projecttemplate',
            name='generated_from',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
