# Generated by Django 5.2 on 2026-06-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktemplate',
            name='status',
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20),
        ),
    ]
