# Generated by Django 5.2 on 2026-06-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_remove_tasktemplate_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=149),
        ),
        migrations.AlterField(
            model_name='projecttemplate',
            name='name',
            field=models.CharField(max_length=149),
        ),
    ]
