# Generated by Django 5.2 on 2026-06-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=136),
        ),
        migrations.AlterField(
            model_name='projecttemplate',
            name='name',
            field=models.CharField(max_length=71),
        ),
    ]
