# Generated by Django 5.2 on 2026-06-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_alter_project_name_alter_projecttemplate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttemplate',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
