# Generated by Django 5.2 on 2026-06-06 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_alter_projecttemplate_name'),
    ]

    operations = [
    ]
