# Generated by Django 5.2 on 2026-06-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_add_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archivado'),
        ),
    ]
