# Generated by Django 5.2 on 2026-06-10 07:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_taskcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watched_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
