# Generated by Django 6.0.4 on 2026-06-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_taskcomment_options_task_watchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='request_kind',
            field=models.CharField(blank=True, choices=[('DELEGATED', 'Delegada'), ('OPTIONAL', 'Opcional'), ('IMPROVEMENT', 'Mejora'), ('ROUTINE', 'Rutinaria'), ('SCHEDULED', 'Programada'), ('MITIGATION', 'Mitigación'), ('IMMEDIATE', 'Inmediata')], max_length=20),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='type',
            field=models.CharField(choices=[('COMMENT', 'Comentario'), ('REQUEST', 'Solicitud')], default='COMMENT', max_length=10),
        ),
    ]
