# Generated by Django 5.2 on 2026-06-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_taskcomment_completed_taskcomment_request_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
