# Generated by Django 5.2 on 2026-06-15 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_taskcomment_resolved_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcomment',
            old_name='completed',
            new_name='resolved',
        ),
    ]
