# Generated by Django 5.2 on 2026-06-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_task_cancelled_at_task_completed_at_task_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcomment',
            name='request_kind',
            field=models.CharField(blank=True, choices=[('IMMEDIATE', 'Inmediata'), ('MITIGATION', 'Mitigación'), ('SCHEDULED', 'Programada'), ('ROUTINE', 'Rutinaria'), ('IMPROVEMENT', 'Mejora'), ('OPTIONAL', 'Opcional'), ('DELEGATED', 'Delegada')], max_length=20),
        ),
    ]
