# Generated by Django 5.2 on 2026-06-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_alter_taskcomment_request_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcomment',
            name='request_kind',
            field=models.CharField(blank=True, choices=[('IMMEDIATE', 'Inmediata'), ('SCHEDULED', 'Programada'), ('ROUTINE', 'Rutinaria'), ('MITIGATION', 'Atenuación'), ('IMPROVEMENT', 'Mejora'), ('OPTIONAL', 'Opcional'), ('DELEGATED', 'Delegada')], max_length=20),
        ),
    ]
