# Generated by Django 5.2 on 2026-07-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_alter_taskcomment_request_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='request_kind',
            field=models.CharField(blank=True, choices=[('IMMEDIATE', 'Inmediata'), ('SCHEDULED', 'Programada'), ('ROUTINE', 'Rutinaria'), ('MITIGATION', 'Revisión'), ('IMPROVEMENT', 'Mejora'), ('OPTIONAL', 'Opcional'), ('DELEGATED', 'Delegada')], max_length=20),
        ),
    ]
