# Generated by Django 5.2 on 2026-07-05 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_task_estimated_time_alter_taskcomment_request_kind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='estimated_time',
            new_name='estimated',
        ),
    ]
