# Generated by Django 5.2 on 2026-07-06 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_rename_estimated_time_task_estimated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='estimated',
            new_name='time_estimated',
        ),
    ]
