# Generated by Django 5.2 on 2026-07-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_rename_estimated_task_time_estimated'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='frozen_time_elapsed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='frozen_time_remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
