# Generated by Django 5.2 on 2026-07-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_task_frozen_time_elapsed_task_frozen_time_remaining'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='frozen_time_remaining',
            new_name='remaining_minutes',
        ),
        migrations.RemoveField(
            model_name='task',
            name='frozen_time_elapsed',
        ),
        migrations.AddField(
            model_name='task',
            name='active_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='elapsed_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='frozen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
