# Generated by Django 5.2 on 2026-07-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_alter_task_due_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
