# Generated by Django 5.2 on 2026-07-16 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_project_archived_at'),
        ('tasks', '0030_task_sequence_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='projects.project'),
        ),
    ]
