# apps\reports\demo\catalogs\tasks_catalog.py sirve para:
# definir el catálogo de tareas asociado a cada tipo de proyecto de demostración,
# incluyendo orden, descripción, prioridad, estimación, fase, rol responsable y planificación

# Librerías estándar de Python
# Librerías externas (Django, requests, openpyxl, reportlab, etc.)
# Imports internos de proyecto/apps
from .project_roles import OWNER, MANAGER, MEMBER
from .project_types import WEB, ERP, BI, MOBILE, INFRASTRUCTURE, SECURITY, AUTOMATION
from .task_phases import ANALYSIS, DESIGN, DEVELOPMENT, TESTING, DEPLOYMENT, SUPPORT


# catálogo de tareas
TASK_CATALOG = {

  #web
  WEB: [
    {
      "order": 1,
      "title": "Análisis de requisitos",
      "description": "Reunión con cliente y recopilación de requisitos.",
      "priority": "HIGH",
      "estimate": 5,
      "phase": ANALYSIS,
      "role": MANAGER,
      "planned": True,
    },
    {
      "order": 2,
      "title": "Definición del alcance",
      "description": "Validación funcional con el cliente.",
      "priority": "HIGH",
      "estimate": 2,
      "phase": ANALYSIS,
      "role": OWNER,
      "planned": True,
    },
    {
      "order": 3,
      "title": "Diseño UX",
      "description": "Wireframes y navegación.",
      "priority": "MEDIUM",
      "estimate": 4,
      "phase": DESIGN,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 4,
      "title": "Diseño UI",
      "description": "Diseño visual de pantallas.",
      "priority": "MEDIUM",
      "estimate": 3,
      "phase": DESIGN,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 5,
      "title": "Arquitectura Backend",
      "description": "Diseño de la arquitectura del sistema.",
      "priority": "HIGH",
      "estimate": 4,
      "phase": DEVELOPMENT,
      "role": MANAGER,
      "planned": True,
    },
    {
      "order": 6,
      "title": "Implementación Login",
      "description": "Sistema de autenticación.",
      "priority": "HIGH",
      "estimate": 8,
      "phase": DEVELOPMENT,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 7,
      "title": "Gestión de Clientes",
      "description": "CRUD completo de clientes.",
      "priority": "HIGH",
      "estimate": 10,
      "phase": DEVELOPMENT,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 8,
      "title": "Panel de administración",
      "description": "Gestión de usuarios y permisos.",
      "priority": "MEDIUM",
      "estimate": 6,
      "phase": DEVELOPMENT,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 9,
      "title": "Integración API",
      "description": "Integración con servicios externos.",
      "priority": "HIGH",
      "estimate": 5,
      "phase": DEVELOPMENT,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 10,
      "title": "Pruebas unitarias",
      "description": "Cobertura de pruebas.",
      "priority": "MEDIUM",
      "estimate": 3,
      "phase": TESTING,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 11,
      "title": "Pruebas funcionales",
      "description": "Validación completa del sistema.",
      "priority": "MEDIUM",
      "estimate": 4,
      "phase": TESTING,
      "role": MANAGER,
      "planned": True,
    },
    {
      "order": 12,
      "title": "Preparación producción",
      "description": "Configuración del entorno productivo.",
      "priority": "HIGH",
      "estimate": 2,
      "phase": DEPLOYMENT,
      "role": OWNER,
      "planned": True,
    },
    {
      "order": 13,
      "title": "Despliegue",
      "description": "Publicación en producción.",
      "priority": "HIGH",
      "estimate": 2,
      "phase": DEPLOYMENT,
      "role": OWNER,
      "planned": True,
    },
    {
      "order": 14,
      "title": "Seguimiento postproducción",
      "description": "Resolución de incidencias iniciales.",
      "priority": "LOW",
      "estimate": 5,
      "phase": SUPPORT,
      "role": MEMBER,
      "planned": False,
    },
  ],

  #ERP
  ERP: [
    {
      "order": 1,
      "title": "Análisis de procesos",
      "description": "Análisis de los procesos actuales de la organización.",
      "priority": "HIGH",
      "estimate": 5,
      "phase": ANALYSIS,
      "role": MANAGER,
      "planned": True,
    },
    {
      "order": 2,
      "title": "Definición de módulos",
      "description": "Identificación de los módulos necesarios.",
      "priority": "HIGH",
      "estimate": 3,
      "phase": ANALYSIS,
      "role": OWNER,
      "planned": True,
    },
    {
      "order": 3,
      "title": "Diseño de procesos",
      "description": "Diseño de los nuevos procesos de negocio.",
      "priority": "HIGH",
      "estimate": 5,
      "phase": DESIGN,
      "role": MANAGER,
      "planned": True,
    },
    {
      "order": 4,
      "title": "Configuración financiera",
      "description": "Configuración de módulos financieros.",
      "priority": "HIGH",
      "estimate": 7,
      "phase": DEVELOPMENT,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 5,
      "title": "Configuración de compras",
      "description": "Configuración de compras y proveedores.",
      "priority": "MEDIUM",
      "estimate": 6,
      "phase": DEVELOPMENT,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 6,
      "title": "Migración de datos",
      "description": "Migración de información del sistema anterior.",
      "priority": "HIGH",
      "estimate": 10,
      "phase": DEVELOPMENT,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 7,
      "title": "Integración con sistemas externos",
      "description": "Integración con aplicaciones corporativas.",
      "priority": "HIGH",
      "estimate": 8,
      "phase": DEVELOPMENT,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 8,
      "title": "Pruebas de integración",
      "description": "Validación de las integraciones.",
      "priority": "MEDIUM",
      "estimate": 4,
      "phase": TESTING,
      "role": MANAGER,
      "planned": True,
    },
    {
      "order": 9,
      "title": "Pruebas de usuario",
      "description": "Validación por parte de usuarios finales.",
      "priority": "MEDIUM",
      "estimate": 4,
      "phase": TESTING,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 10,
      "title": "Carga inicial",
      "description": "Carga definitiva de información.",
      "priority": "HIGH",
      "estimate": 3,
      "phase": DEPLOYMENT,
      "role": MANAGER,
      "planned": True,
    },
    {
      "order": 11,
      "title": "Puesta en producción",
      "description": "Activación del sistema ERP.",
      "priority": "HIGH",
      "estimate": 2,
      "phase": DEPLOYMENT,
      "role": OWNER,
      "planned": True,
    },
    {
      "order": 12,
      "title": "Soporte inicial",
      "description": "Soporte a usuarios durante la puesta en marcha.",
      "priority": "LOW",
      "estimate": 5,
      "phase": SUPPORT,
      "role": MEMBER,
      "planned": False,
    },
  ],

  #business intelligence
  BI: [
    {
      "order": 1,
      "title": "Identificar indicadores",
      "description": "Definición de los principales indicadores de negocio.",
      "priority": "HIGH",
      "estimate": 3,
      "phase": ANALYSIS,
      "role": MANAGER,
      "planned": True,
    },
    {
      "order": 2,
      "title": "Analizar fuentes de datos",
      "description": "Identificación y análisis de las fuentes disponibles.",
      "priority": "HIGH",
      "estimate": 4,
      "phase": ANALYSIS,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 3,
      "title": "Diseñar modelo de datos",
      "description": "Diseño del modelo analítico.",
      "priority": "HIGH",
      "estimate": 5,
      "phase": DESIGN,
      "role": MANAGER,
      "planned": True,
    },
    {
      "order": 4,
      "title": "Diseñar dashboard",
      "description": "Diseño de la estructura de los cuadros de mando.",
      "priority": "MEDIUM",
      "estimate": 4,
      "phase": DESIGN,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 5,
      "title": "Construir ETL",
      "description": "Implementación de procesos de extracción y transformación.",
      "priority": "HIGH",
      "estimate": 8,
      "phase": DEVELOPMENT,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 6,
      "title": "Construir modelo analítico",
      "description": "Implementación del modelo de datos.",
      "priority": "HIGH",
      "estimate": 7,
      "phase": DEVELOPMENT,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 7,
      "title": "Crear indicadores",
      "description": "Implementación de KPIs y métricas.",
      "priority": "HIGH",
      "estimate": 5,
      "phase": DEVELOPMENT,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 8,
      "title": "Validar datos",
      "description": "Comprobación de calidad y consistencia.",
      "priority": "MEDIUM",
      "estimate": 4,
      "phase": TESTING,
      "role": MANAGER,
      "planned": True,
    },
    {
      "order": 9,
      "title": "Validación con usuarios",
      "description": "Revisión de los informes con usuarios finales.",
      "priority": "MEDIUM",
      "estimate": 3,
      "phase": TESTING,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 10,
      "title": "Publicación de dashboards",
      "description": "Publicación de los cuadros de mando.",
      "priority": "HIGH",
      "estimate": 2,
      "phase": DEPLOYMENT,
      "role": OWNER,
      "planned": True,
    },
    {
      "order": 11,
      "title": "Formación de usuarios",
      "description": "Formación sobre el uso de los dashboards.",
      "priority": "LOW",
      "estimate": 3,
      "phase": SUPPORT,
      "role": MEMBER,
      "planned": False,
    },
  ],

  #móvil
  MOBILE: [
    {
      "order": 1,
      "title": "Análisis de funcionalidades",
      "description": "Definición de funcionalidades de la aplicación.",
      "priority": "HIGH",
      "estimate": 4,
      "phase": ANALYSIS,
      "role": MANAGER,
      "planned": True,
    },
    {
      "order": 2,
      "title": "Diseño de navegación",
      "description": "Definición de navegación y experiencia móvil.",
      "priority": "MEDIUM",
      "estimate": 4,
      "phase": DESIGN,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 3,
      "title": "Diseño de interfaz",
      "description": "Diseño visual de la aplicación.",
      "priority": "MEDIUM",
      "estimate": 5,
      "phase": DESIGN,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 4,
      "title": "Configuración del proyecto móvil",
      "description": "Preparación de la estructura de la aplicación.",
      "priority": "HIGH",
      "estimate": 3,
      "phase": DEVELOPMENT,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 5,
      "title": "Implementación de autenticación",
      "description": "Login y gestión de sesiones.",
      "priority": "HIGH",
      "estimate": 6,
      "phase": DEVELOPMENT,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 6,
      "title": "Implementación de funcionalidades",
      "description": "Desarrollo de las funcionalidades principales.",
      "priority": "HIGH",
      "estimate": 10,
      "phase": DEVELOPMENT,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 7,
      "title": "Integración con API",
      "description": "Integración con servicios backend.",
      "priority": "HIGH",
      "estimate": 6,
      "phase": DEVELOPMENT,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 8,
      "title": "Pruebas en dispositivos",
      "description": "Pruebas en diferentes dispositivos y tamaños.",
      "priority": "MEDIUM",
      "estimate": 5,
      "phase": TESTING,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 9,
      "title": "Pruebas de rendimiento",
      "description": "Comprobación del rendimiento de la aplicación.",
      "priority": "MEDIUM",
      "estimate": 4,
      "phase": TESTING,
      "role": MANAGER,
      "planned": True,
    },
    {
      "order": 10,
      "title": "Preparación de publicación",
      "description": "Preparación para las tiendas de aplicaciones.",
      "priority": "HIGH",
      "estimate": 3,
      "phase": DEPLOYMENT,
      "role": OWNER,
      "planned": True,
    },
    {
      "order": 11,
      "title": "Publicación",
      "description": "Publicación de la aplicación.",
      "priority": "HIGH",
      "estimate": 2,
      "phase": DEPLOYMENT,
      "role": OWNER,
      "planned": True,
    },
    {
      "order": 12,
      "title": "Monitorización inicial",
      "description": "Seguimiento de incidencias después del lanzamiento.",
      "priority": "LOW",
      "estimate": 5,
      "phase": SUPPORT,
      "role": MEMBER,
      "planned": False,
    },
  ],

  #infraestructura
  INFRASTRUCTURE: [
    {
      "order": 1,
      "title": "Inventario de infraestructura",
      "description": "Inventario de servidores, redes y servicios.",
      "priority": "HIGH",
      "estimate": 4,
      "phase": ANALYSIS,
      "role": MANAGER,
      "planned": True,
    },
    {
      "order": 2,
      "title": "Análisis de capacidad",
      "description": "Análisis de capacidad y necesidades futuras.",
      "priority": "HIGH",
      "estimate": 4,
      "phase": ANALYSIS,
      "role": MANAGER,
      "planned": True,
    },
    {
      "order": 3,
      "title": "Diseño de arquitectura",
      "description": "Diseño de la arquitectura objetivo.",
      "priority": "HIGH",
      "estimate": 6,
      "phase": DESIGN,
      "role": MANAGER,
      "planned": True,
    },
    {
      "order": 4,
      "title": "Configuración de servidores",
      "description": "Configuración de servidores y máquinas virtuales.",
      "priority": "HIGH",
      "estimate": 7,
      "phase": DEVELOPMENT,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 5,
      "title": "Configuración de red",
      "description": "Configuración de redes y comunicaciones.",
      "priority": "HIGH",
      "estimate": 6,
      "phase": DEVELOPMENT,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 6,
      "title": "Configuración de backups",
      "description": "Configuración de copias de seguridad.",
      "priority": "MEDIUM",
      "estimate": 4,
      "phase": DEVELOPMENT,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 7,
      "title": "Monitorización",
      "description": "Configuración de monitorización y alertas.",
      "priority": "MEDIUM",
      "estimate": 5,
      "phase": DEVELOPMENT,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 8,
      "title": "Pruebas de disponibilidad",
      "description": "Comprobación de disponibilidad y recuperación.",
      "priority": "HIGH",
      "estimate": 4,
      "phase": TESTING,
      "role": MANAGER,
      "planned": True,
    },
    {
      "order": 9,
      "title": "Pruebas de rendimiento",
      "description": "Pruebas de carga y rendimiento.",
      "priority": "MEDIUM",
      "estimate": 5,
      "phase": TESTING,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 10,
      "title": "Migración",
      "description": "Migración de servicios a la nueva infraestructura.",
      "priority": "HIGH",
      "estimate": 8,
      "phase": DEPLOYMENT,
      "role": MANAGER,
      "planned": True,
    },
    {
      "order": 11,
      "title": "Puesta en servicio",
      "description": "Activación de la infraestructura.",
      "priority": "HIGH",
      "estimate": 2,
      "phase": DEPLOYMENT,
      "role": OWNER,
      "planned": True,
    },
    {
      "order": 12,
      "title": "Monitorización postmigración",
      "description": "Seguimiento de la infraestructura después de la migración.",
      "priority": "LOW",
      "estimate": 5,
      "phase": SUPPORT,
      "role": MEMBER,
      "planned": False,
    },
  ],

  #seguridad
  SECURITY: [
    {
      "order": 1,
      "title": "Análisis de riesgos",
      "description": "Identificación de amenazas y riesgos.",
      "priority": "HIGH",
      "estimate": 6,
      "phase": ANALYSIS,
      "role": MANAGER,
      "planned": True,
    },
    {
      "order": 2,
      "title": "Inventario de activos",
      "description": "Inventario de activos de información.",
      "priority": "HIGH",
      "estimate": 5,
      "phase": ANALYSIS,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 3,
      "title": "Definición de controles",
      "description": "Selección de controles de seguridad.",
      "priority": "HIGH",
      "estimate": 6,
      "phase": DESIGN,
      "role": MANAGER,
      "planned": True,
    },
    {
      "order": 4,
      "title": "Diseño del plan de seguridad",
      "description": "Definición del plan de tratamiento de riesgos.",
      "priority": "HIGH",
      "estimate": 4,
      "phase": DESIGN,
      "role": MANAGER,
      "planned": True,
    },
    {
      "order": 5,
      "title": "Implementación de controles",
      "description": "Aplicación de controles de seguridad.",
      "priority": "HIGH",
      "estimate": 10,
      "phase": DEVELOPMENT,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 6,
      "title": "Configuración de accesos",
      "description": "Revisión y configuración de permisos.",
      "priority": "HIGH",
      "estimate": 5,
      "phase": DEVELOPMENT,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 7,
      "title": "Auditoría interna",
      "description": "Revisión interna del cumplimiento.",
      "priority": "HIGH",
      "estimate": 6,
      "phase": TESTING,
      "role": MANAGER,
      "planned": True,
    },
    {
      "order": 8,
      "title": "Pruebas de seguridad",
      "description": "Pruebas técnicas de seguridad.",
      "priority": "HIGH",
      "estimate": 5,
      "phase": TESTING,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 9,
      "title": "Corrección de vulnerabilidades",
      "description": "Corrección de vulnerabilidades detectadas.",
      "priority": "HIGH",
      "estimate": 7,
      "phase": DEVELOPMENT,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 10,
      "title": "Preparación de certificación",
      "description": "Preparación de documentación para certificación.",
      "priority": "MEDIUM",
      "estimate": 5,
      "phase": DEPLOYMENT,
      "role": OWNER,
      "planned": True,
    },
    {
      "order": 11,
      "title": "Auditoría de certificación",
      "description": "Preparación y acompañamiento de la auditoría.",
      "priority": "HIGH",
      "estimate": 4,
      "phase": DEPLOYMENT,
      "role": OWNER,
      "planned": True,
    },
    {
      "order": 12,
      "title": "Seguimiento de cumplimiento",
      "description": "Seguimiento periódico de los controles.",
      "priority": "LOW",
      "estimate": 5,
      "phase": SUPPORT,
      "role": MEMBER,
      "planned": False,
    },
  ],

  #automatización
  AUTOMATION: [
    {
      "order": 1,
      "title": "Identificar procesos automatizables",
      "description": "Identificación de procesos candidatos a automatización.",
      "priority": "HIGH",
      "estimate": 4,
      "phase": ANALYSIS,
      "role": MANAGER,
      "planned": True,
    },
    {
      "order": 2,
      "title": "Analizar reglas de negocio",
      "description": "Documentación de reglas y excepciones.",
      "priority": "HIGH",
      "estimate": 4,
      "phase": ANALYSIS,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 3,
      "title": "Diseñar flujo automatizado",
      "description": "Diseño del flujo completo de automatización.",
      "priority": "HIGH",
      "estimate": 5,
      "phase": DESIGN,
      "role": MANAGER,
      "planned": True,
    },
    {
      "order": 4,
      "title": "Diseñar gestión de errores",
      "description": "Definición de excepciones y recuperación.",
      "priority": "MEDIUM",
      "estimate": 3,
      "phase": DESIGN,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 5,
      "title": "Implementar automatización",
      "description": "Desarrollo del proceso automatizado.",
      "priority": "HIGH",
      "estimate": 10,
      "phase": DEVELOPMENT,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 6,
      "title": "Integrar sistemas",
      "description": "Integración con los sistemas involucrados.",
      "priority": "HIGH",
      "estimate": 7,
      "phase": DEVELOPMENT,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 7,
      "title": "Configurar ejecución programada",
      "description": "Configuración de ejecuciones automáticas.",
      "priority": "MEDIUM",
      "estimate": 3,
      "phase": DEVELOPMENT,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 8,
      "title": "Pruebas del flujo",
      "description": "Validación del flujo automatizado.",
      "priority": "HIGH",
      "estimate": 4,
      "phase": TESTING,
      "role": MANAGER,
      "planned": True,
    },
    {
      "order": 9,
      "title": "Pruebas de errores",
      "description": "Validación de escenarios excepcionales.",
      "priority": "MEDIUM",
      "estimate": 3,
      "phase": TESTING,
      "role": MEMBER,
      "planned": True,
    },
    {
      "order": 10,
      "title": "Puesta en producción",
      "description": "Activación de la automatización.",
      "priority": "HIGH",
      "estimate": 2,
      "phase": DEPLOYMENT,
      "role": OWNER,
      "planned": True,
    },
    {
      "order": 11,
      "title": "Monitorización",
      "description": "Seguimiento de ejecuciones y errores.",
      "priority": "MEDIUM",
      "estimate": 5,
      "phase": SUPPORT,
      "role": MEMBER,
      "planned": False,
    },
    {
      "order": 12,
      "title": "Optimización",
      "description": "Mejora del proceso después de la puesta en producción.",
      "priority": "LOW",
      "estimate": 4,
      "phase": SUPPORT,
      "role": MEMBER,
      "planned": False,
    },
  ],
}
