# Generated by Django 5.2 on 2026-07-24 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0027_project_archived_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProgressSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('completion_percentage', models.PositiveSmallIntegerField(default=0)),
                ('is_interpolated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_snapshots', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'month')},
            },
        ),
    ]
